// ===== FEATURED PROJECTS =====
export const projects = [
  {
    id: 1,
    title: "Lead-Thing - Advanced Leadership & Team Management Platform",
    description:
      "Comprehensive platform for team leadership, project management, and collaborative decision-making. Features advanced analytics, team performance tracking, and AI-powered insights for building super happy, close-knit teams.",
    icon: "Briefcase",
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Node.js",
      "PostgreSQL",
      "AI Integration",
      "Real-time Analytics",
    ],
    category: "leadership",
    achievements: [
      "Advanced team dynamics tracking",
      "AI-powered leadership insights",
      "Collaborative goal-setting tools",
      "Real-time team happiness metrics",
    ],
    featured: true,
    status: "In Development",
  },
  {
    id: 2,
    title: "Anywhere-Widgets - Universal Widget Engine",
    description:
      "Revolutionary universal widget engine with SSR client hydration that runs across 20+ platforms. Built my own Next.js-like widget framework with custom compiler, Preact signals for minimal bundle size, and native performance even in webviews. Single codebase for widgets running on Shopify, React, Vue, mobile apps, and more.",
    icon: "Globe",
    technologies: [
      "TypeScript",
      "Custom SSR Engine",
      "Preact Signals",
      "Custom Compiler",
      "Iframe Widgets",
      "Cross-Platform",
      "Kotlin/Swift Wrappers",
      "WebView Integration",
    ],
    category: "framework",
    achievements: [
      "Built Next.js-like widget framework with custom compiler",
      "SSR + client hydration for multiple iframe widgets in parallel",
      "Single codebase running across 20+ platforms",
      "Native performance even in webviews with 100% flexible styling",
      "Preact signals for minimum bundle size and reactivity",
      "Custom 'use client' implementation and compiler",
    ],
    featured: true,
    status: "In Development - Core Engine Complete",
  },
  {
    id: 3,
    title: "Next-Vibe - AI-Native WordPress Successor",
    description:
      "Spiritual successor to WordPress but AI-native. Built on Next.js with my own framework around it. Single API definition becomes CLI command, web page, AI tool, and cron job. Uses Zod schema for type-safe input/output/UI definition. Each API is a tool the AI can use based on user roles.",
    icon: "Zap",
    technologies: [
      "TypeScript",
      "Next.js Framework",
      "Zod Schema",
      "AI Tool Integration",
      "CLI Generation",
      "Multi-Interface APIs",
      "Cron Jobs",
      "Role-Based AI",
    ],
    category: "ai-ml",
    achievements: [
      "Single definition.ts creates CLI, Web, AI, and Cron interfaces",
      "AI-native architecture with role-based tool access",
      "Auto-generated UI from Zod schema definitions",
      "Multi-interface API system (CLI/Web/AI/Cron)",
      "Type-safe end-to-end development experience",
      "Revolutionary approach to content management",
    ],
    featured: true,
    status: "In Development - Core Architecture Complete",
  },
  {
    id: 4,
    title: "Beauty Studio Management System",
    description:
      "Complete website and management system for beauty studios with partner portal for multiple locations, appointment management, and online booking capabilities. Features static pages for SEO optimization and privacy-focused analytics.",
    icon: "Calendar",
    technologies: [
      "Next.js",
      "React",
      "Python",
      "Flask",
      "Docker",
      "Caddy",
      "Matomo",
    ],
    category: "fullstack",
    achievements: [
      "Multi-location partner portal",
      "Automated deployment with Git/Docker",
      "Privacy-focused analytics with Matomo",
      "SEO-optimized static pages",
    ],
    featured: true,
    url: "https://faceart.studio",
  },
  {
    id: 5,
    title: "OctoBot Strategy Designer & Trading Platform",
    description:
      "Collaboration on open-source investing bot project with sophisticated strategy designer. Allows beginners to create complex strategies, simulate them, improve automatically using genetic algorithms, and execute live trading via broker APIs.",
    icon: "TrendingUp",
    technologies: [
      "Python",
      "Cython",
      "Flask",
      "React",
      "JavaScript",
      "Async/Threading",
      "NumPy",
      "Pandas",
      "SQLAlchemy",
      "Plotly",
      "MUI",
      "Bootstrap",
    ],
    category: "ai-ml",
    achievements: [
      "Genetic algorithm optimization",
      "Real-time strategy simulation",
      "Live trading integration",
      "Advanced strategy designer UI",
      "Continuous coaching and code reviews",
    ],
    featured: true,
    url: "https://octobot.online",
  },
  {
    id: 6,
    title: "Trading Bot User Interface & Customized OctoBot Backend",
    description:
      "Developed a sophisticated trading bot with real-time market analysis, machine learning decision-making, and deep neural networks for advanced trading strategies.",
    icon: "TrendingUp",
    technologies: [
      "Python",
      "JavaScript",
      "React",
      "Machine Learning",
      "Neural Networks",
      "WebSocket",
      "REST API",
    ],
    category: "ai-ml",
    achievements: [
      "Real-time market analysis integration",
      "Advanced ML-based decision making",
      "Custom OctoBot backend modifications",
      "Sophisticated trading algorithms",
    ],
    featured: true,
  },
  {
    id: 11,
    title: "AI-Powered Data Analytics Platform",
    description:
      "Built a comprehensive data analytics platform that transforms complex datasets into actionable insights using advanced machine learning and predictive analytics.",
    icon: "Database",
    technologies: [
      "Python",
      "TensorFlow",
      "PostgreSQL",
      "React",
      "D3.js",
      "Docker",
      "AWS",
    ],
    category: "ai-ml",
    achievements: [
      "Complex dataset processing",
      "Predictive analytics implementation",
      "Interactive data visualizations",
      "Scalable cloud architecture",
    ],
    featured: true,
  },
  {
    id: 12,
    title: "Open Source Library Enhancement",
    description:
      "Revamped and enhanced multiple open-source libraries, improving performance, adding new features, and modernizing codebases for better developer experience.",
    icon: "Code",
    technologies: [
      "TypeScript",
      "Node.js",
      "Jest",
      "GitHub Actions",
      "npm",
      "Documentation",
    ],
    category: "opensource",
    achievements: [
      "Performance optimizations",
      "Modern TypeScript migration",
      "Comprehensive test coverage",
      "Enhanced developer documentation",
    ],
    featured: true,
  },
  {
    id: 13,
    title: "Algorithmic Trading System",
    description:
      "Designed and implemented sophisticated algorithmic trading systems with advanced risk management, backtesting capabilities, and real-time execution.",
    icon: "Cpu",
    technologies: [
      "Python",
      "NumPy",
      "Pandas",
      "QuantLib",
      "Redis",
      "PostgreSQL",
      "Docker",
    ],
    category: "fintech",
    achievements: [
      "Advanced risk management",
      "Backtesting framework",
      "Real-time execution engine",
      "Performance monitoring",
    ],
    featured: false,
  },
  {
    id: 14,
    title: "Full Stack Web Applications",
    description:
      "Created multiple scalable web applications with modern architectures, focusing on performance, user experience, and maintainable code.",
    icon: "Zap",
    technologies: [
      "Next.js",
      "React",
      "Node.js",
      "PostgreSQL",
      "Tailwind CSS",
      "Vercel",
    ],
    category: "fullstack",
    achievements: [
      "Scalable architecture design",
      "Optimized performance",
      "Modern UI/UX implementation",
      "Production deployment",
    ],
    featured: false,
  },
  {
    id: 15,
    title: "AI Assistant Integration",
    description:
      "Integrated advanced AI capabilities into web applications, including natural language processing, intelligent chat systems, and automated workflows.",
    icon: "Bot",
    technologies: [
      "OpenAI API",
      "LangChain",
      "React",
      "TypeScript",
      "Vector Databases",
      "Streaming",
    ],
    category: "ai-ml",
    achievements: [
      "Natural language processing",
      "Intelligent chat systems",
      "Automated workflow creation",
      "Real-time AI responses",
    ],
    featured: false,
  },
  {
    id: 7,
    title: "OctoBot Trading Strategy Designer",
    description:
      "Collaboration on open source investing bot project. Developed the strategy designer (private beta) allowing beginners to create complex strategies, simulate them, improve them automatically using genetic algorithms, and execute live trading with real money through broker APIs.",
    icon: "TrendingUp",
    technologies: [
      "Python",
      "Cython",
      "Flask",
      "React",
      "Async/Threading",
      "NumPy",
      "Pandas",
      "SQLAlchemy",
      "MUI",
      "Bootstrap",
      "Plotly",
      "JSON Editor",
    ],
    category: "fintech",
    achievements: [
      "Built comprehensive strategy designer for complex trading algorithms",
      "Implemented genetic algorithm for automatic strategy optimization",
      "Integrated live trading with real money through broker APIs",
      "Created simulation and backtesting framework",
      "Developed user-friendly interface for beginners to create complex strategies",
      "Continuous coaching and code reviews with project developer team",
    ],
    featured: true,
    status: "Production - https://octobot.online",
  },
  {
    id: 8,
    title: "FaceArt Beauty Studio - Multi-Location Management Platform",
    description:
      "Complete website and management system for beauty studio with partner portal for multiple locations, appointment management, and online booking capabilities. Features static pages for SEO optimization and privacy-focused analytics.",
    icon: "Briefcase",
    technologies: [
      "Next.js",
      "React",
      "Python",
      "Flask",
      "Docker",
      "Caddy",
      "Matomo Analytics",
      "Git Automation",
      "Static Site Generation",
    ],
    category: "fullstack",
    achievements: [
      "Built complete multi-location management system",
      "Implemented partner portal for multiple beauty studio locations",
      "Created appointment management and online booking system",
      "Automated deployment with Git, Docker, and Caddy",
      "Privacy-focused analytics with self-hosted Matomo instead of third-party providers",
      "SEO-optimized static pages for better search engine performance",
    ],
    featured: true,
    status: "Production - https://faceart.studio",
  },
  {
    id: 9,
    title: "Sovendus Developer Hub & Testing Platform",
    description:
      "Revolutionary developer tools and self-service solutions that transformed partner onboarding. Built comprehensive documentation platform and testing app enabling self-diagnosis for 99% of onboarding issues, dramatically reducing support load.",
    icon: "Code",
    technologies: [
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "Flutter",
      "React Native",
      "Kotlin",
      "Swift",
      "PHP",
      "Docker",
      "Documentation Platforms",
    ],
    category: "integration",
    achievements: [
      "Built developer-hub.sovendus.com documentation platform",
      "Created Sovendus testing app enabling self-diagnosis for 99% of onboarding issues",
      "Developed 20+ platform-specific plugins (Shopify, Magento, Shopware, Flutter, React Native, Kotlin, Swift)",
      "Implemented unified codebase architecture with platform-specific overrides",
      "Shifted support from reactive to proactive long-term solutions",
      "Left comprehensive documentation and maintainable foundation for successor",
    ],
    featured: true,
    status: "Production - Sovendus Integration Team Lead",
  },
  {
    id: 10,
    title: "Samsung Business Tech Support - Global Team Leadership",
    description:
      "Led Swiss Business Tech Support Team (10 people) for Samsung business products. Resolved complex issues that no one else could solve, often resulting in bug fixes and new features in coordination with global teams and product developers.",
    icon: "Briefcase",
    technologies: [
      "Samsung Knox Suite MDM",
      "MagicInfo",
      "LED/LCD Wall Systems",
      "Mobile Business Hardware",
      "Python",
      "JavaScript",
      "React.js",
      "SQL",
      "REST APIs",
      "Git",
      "Docker",
    ],
    category: "leadership",
    achievements: [
      "Orchestrated and mentored highly skilled Swiss Business Tech Support Team (10 people)",
      "Resolved issues that no one else could solve, coordinating with global teams",
      "Implemented bug fixes and new features with product/feature developer support teams",
      "Conducted advanced training courses on supported products and industry knowledge",
      "Achieved remarkable KPI improvements in resolution rate and response time",
      "Reduced escalations through comprehensive training programs",
    ],
    featured: true,
    status: "Completed - Samsung Switzerland 2018-2020",
  },
] as const;

// ===== PROJECT CATEGORIES =====
export const projectCategories = [
  { id: "all", label: "All Projects" },
  { id: "leadership", label: "Leadership & Management" },
  { id: "integration", label: "Integration & APIs" },
  { id: "framework", label: "Frameworks & Tools" },
  { id: "ai-ml", label: "AI & ML" },
  { id: "fullstack", label: "Full Stack" },
  { id: "fintech", label: "FinTech" },
  { id: "opensource", label: "Open Source" },
] as const;
