// ===== PROFESSIONAL EXPERIENCE =====
export const experience = [
  {
    title: "Integration Team Lead",
    company: "Sovendus",
    location: "Remote",
    period: "Sep 2023 - Sep 2025",
    type: "Full-time",
    description:
      "Led the integration team and revolutionized partner onboarding by building comprehensive developer tools and self-service solutions.",
    achievements: [
      "Built developer-hub.sovendus.com documentation platform (plugins and testing app are linked there)",
      "Created Sovendus testing app enabling self-diagnosis for 99% of onboarding issues",
      "Developed 20+ platform-specific plugins (Shopify, Magento, Shopware, Flutter, React Native, Kotlin, Swift)",
      "Implemented unified codebase architecture with platform-specific overrides",
      "Shifted support from reactive to proactive long-term solutions",
      "Left comprehensive documentation and maintainable foundation for successor",
      "Reduced support tickets significantly through innovative self-service tools",
    ],
    technologies: [
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "Python",
      "PHP",
      "Swift",
      "Kotlin",
      "Flutter",
      "React Native",
      "Docker",
      "Git",
      "REST API",
      "Webhook Integration",
      "Plugin Development",
      "Documentation",
      "Testing Frameworks",
    ],
  },
  {
    title: "Freelance AI Trading Systems Developer",
    company: "a42 trading solutions",
    location: "Switzerland",
    period: "Mar 2018 - Present",
    type: "Freelance",
    description:
      "Developing sophisticated AI-driven trading systems with machine learning decision-making and real-time market analysis.",
    achievements: [
      "Built sophisticated trading algorithms with ML decision-making",
      "Implemented real-time market analysis and risk management",
      "Developed custom trading interfaces and portfolio management tools",
      "Created automated trading strategies with deep neural networks",
    ],
    technologies: [
      "Python",
      "JavaScript",
      "React",
      "Machine Learning",
      "Neural Networks",
      "TensorFlow",
      "PyTorch",
      "WebSocket",
      "REST API",
      "PostgreSQL",
      "Redis",
    ],
  },
  {
    title: "Business Support Engineer - Team Leader",
    company: "Samsung Switzerland",
    location: "Switzerland",
    period: "Sep 2018 - Sep 2020",
    type: "Full-time",
    description:
      "Led Swiss Business Tech Support Team, handling complex software troubleshooting and hardware repairs for Samsung's business product line.",
    achievements: [
      "Managed and mentored technical support team",
      "Handled complex enterprise-level technical issues",
      "Improved support processes and response times",
      "Developed internal tools for efficient problem resolution",
    ],
    technologies: [
      "Technical Support",
      "Hardware Diagnostics",
      "Software Troubleshooting",
      "Team Leadership",
      "Process Optimization",
      "Documentation",
    ],
  },
  {
    title: "Tech Support Engineer - Team Leader - Administrator",
    company: "netsepp KG, Hallein (now viybs.com)",
    location: "Austria",
    period: "Mar 2016 - Jan 2019",
    type: "Full-time",
    description:
      "Led transformative overhaul of internal business processes and workflows within ERP system while managing support engineering team.",
    achievements: [
      "Spearheaded transformative overhaul of internal business processes in ERP system",
      "Led proficient support engineering team for hardware/software solutions",
      "Crafted comprehensive technical documentation and training materials",
      "Delivered exceptional IT consultancy services to private customers and SMEs",
    ],
    technologies: [
      "Python",
      "JavaScript",
      "React.js",
      "SQL",
      "Flask",
      "Odoo",
      "Docker",
      "Git",
      "REST API",
    ],
  },
  {
    title: "Tech Support Engineer - Team Leader",
    company: "techfreaque Salzburg",
    location: "Austria",
    period: "Aug 2013 - Sep 2016",
    type: "Full-time",
    description:
      "Engineered optimized internal infrastructure and guided skilled support team while managing diverse technological landscape.",
    achievements: [
      "Built and optimized internal infrastructure systems",
      "Led and mentored technical support team",
      "Managed diverse technology stack and integrations",
      "Developed automated solutions for common technical issues",
    ],
    technologies: [
      "System Administration",
      "Infrastructure Management",
      "Team Leadership",
      "Process Automation",
      "Technical Support",
      "Documentation",
    ],
  },
] as const;

// ===== EDUCATION & CONTINUOUS LEARNING =====
export const education = [
  {
    category: "JavaScript/TypeScript Ecosystem",
    period: "2012 - Present",
    description: "Deep dive into modern JavaScript and TypeScript development",
    achievements: [
      "Mastered ES6+ features, async patterns, and advanced JavaScript concepts",
      "Expert-level TypeScript with complex generics and architectural design",
      "Advanced understanding of JavaScript engines and performance optimization",
      "Built custom frameworks and libraries from scratch",
    ],
    technologies: [
      "JavaScript",
      "TypeScript",
      "Node.js",
      "V8 Engine",
      "Performance Optimization",
    ],
  },
  {
    category: "React/Next.js/SSR Framework Development",
    period: "2015 - Present",
    description:
      "Comprehensive exploration of React ecosystem and server-side rendering",
    achievements: [
      "Expert in React, Next.js, and modern React patterns",
      "Built custom SSR framework similar to Next.js from scratch",
      "Deep understanding of React internals, fiber architecture, and reconciliation",
      "Advanced SSR, SSG, and client hydration techniques",
      "Created universal widget engine with SSR client hydration",
    ],
    technologies: [
      "React",
      "Next.js",
      "Preact",
      "SSR",
      "Client Hydration",
      "Custom Framework Development",
    ],
  },
  {
    category: "AI/ML & Trading Systems",
    period: "2018 - Present",
    description:
      "Extensive study of artificial intelligence, machine learning, and algorithmic trading",
    achievements: [
      "Built sophisticated AI-driven trading algorithms",
      "Implemented genetic algorithms for strategy optimization",
      "Advanced machine learning with TensorFlow and PyTorch",
      "Real-time market analysis and predictive modeling",
      "Risk management and portfolio optimization systems",
    ],
    technologies: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Genetic Algorithms",
      "Quantitative Finance",
      "Real-time Analytics",
    ],
  },
  {
    category: "DevOps & Infrastructure",
    period: "2013 - Present",
    description: "Comprehensive infrastructure management and automation",
    achievements: [
      "Advanced Docker containerization and orchestration",
      "Infrastructure as Code with automated deployments",
      "GNU/Linux system administration and optimization",
      "Advanced networking, security, and monitoring",
      "Built scalable, high-performance production systems",
    ],
    technologies: [
      "Docker",
      "GNU/Linux",
      "Nginx",
      "PostgreSQL",
      "Redis",
      "Git",
      "Automation",
      "Monitoring",
    ],
  },
  {
    category: "Mobile & Cross-Platform Development",
    period: "2016 - Present",
    description: "Native and cross-platform mobile application development",
    achievements: [
      "Native iOS development with Swift",
      "Native Android development with Kotlin",
      "Cross-platform development with Flutter and React Native",
      "Built 20+ platform-specific plugins and integrations",
      "Advanced understanding of mobile architecture and performance",
    ],
    technologies: [
      "Swift",
      "Kotlin",
      "Flutter",
      "React Native",
      "iOS SDK",
      "Android SDK",
      "Mobile Architecture",
    ],
  },
  {
    category: "Formal Education",
    period: "2007 - 2011",
    description: "Professional apprenticeship and foundational education",
    achievements: [
      "Completed apprenticeship as car technician (2007-2011)",
      "Specialized in Ferrari, Maserati, Aston Martin & Bentley",
      "Advanced diagnosis, maintenance, and repair of complex systems",
      "Electronic systems integration and retrofitting",
      "Internal IT support and technical problem-solving",
      "Personality, communication, and professional development seminars",
    ],
    technologies: [
      "Automotive Systems",
      "Electronic Integration",
      "Diagnostic Tools",
      "Technical Problem-Solving",
    ],
  },
  {
    category: "Continuous Learning & Self-Study",
    period: "2012 - Present",
    description: "Ongoing professional development and skill expansion",
    achievements: [
      "Countless offline/online courses and seminars",
      "Entrepreneurship and business development",
      "Advanced technology and programming concepts",
      "Character formation and leadership development",
      "Marketing, cybersecurity, and hardware/software hacking",
      "Continuous adaptation to emerging technologies",
    ],
    technologies: [
      "Emerging Technologies",
      "Leadership",
      "Entrepreneurship",
      "Cybersecurity",
      "Marketing",
    ],
  },
] as const;
